# Generated by Django 2.2.6 on 2019-10-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('relative_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('list_of_grades', models.CharField(max_length=100)),
                ('cabinet', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_visitors', models.IntegerField()),
                ('workload', models.IntegerField()),
                ('list_of_visitors', models.ManyToManyField(to='meeting_reg.Student')),
            ],
        ),
    ]
